name: Build
run-name: ${{ github.event.pull_request.title || github.ref_name }}

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build --build-cache -x test

      - name: Gradle run tests
        run: ./gradlew test --build-cache

      - name: Build docker image
        run: ./gradlew jibBuildTar # Use jib command instead if you define a registry

      - name: Upload test report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: JUnit Tests
          path: modules/*/build/test-results/**/*.xml
          reporter: java-junit
  dependabot:
    name: 'Dependabot'
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
