name: Build
run-name: ${{ github.event.pull_request.title || github.ref_name }}

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build --build-cache -x test

      - name: Gradle run tests
        run: ./gradlew test --build-cache

      - name: Build docker image
        run: ./gradlew jibBuildTar # Use jib command instead if you define a registry

      - name: Upload test report
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: build/test-results/**/*.xml
          reporter: java-junit